FIREBASE_CREDENTIALS = r"C:\Users\power\Downloads\alpha-zero-d055c-firebase-adminsdk-eslvn-dd227fab08.json"

GEMINI_API_KEY = "AIzaSyB6GrUovhiHEPsRMrSVJ_5R4ibR9c8M_Qg"
PORCUPINE_ACCESS_KEY = "JbLpChpUS8GognDXyL3QUchalwR6tXNAM1R3Pp18ghLQPP6eIq0mcA=="
PORCUPINE_KEYWORD_PATH = "C:\project\ALPHA-Zero"
EXTERNAL_WEBCAM_INDEX = None
EXTERNAL_MIC_INDEX = None 